config/routes.rb
Rails.application.routes.draw do
  resources :mensajes
  root to:"buscar#index"
  get 'buscar/index'
  get 'main/escocencia'
  get 'main/index'
  get 'buscar/create' 
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buscar_controller.rb
class BuscarController < ApplicationController
  def create
  	palabra = params[:keyword]
  	@mensajes = Mensaje.where("Para = ?", palabra)
  	
  	respond_to do |format|
  		format.html { redirect_to root_path }
  		format.json { render json: @mensajes}
  		format.js
  	end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def buscador
  @mensajes = Mensaje.all
  end
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  before_action :set_mensaje, only: [:show, :edit, :update, :destroy]

  # GET /mensajes
  # GET /mensajes.json
  def index
    @mensajes = Mensaje.all
  end

  # GET /mensajes/1
  # GET /mensajes/1.json
  def show
  end

  # GET /mensajes/new
  def new
    @mensaje = Mensaje.new
  end

  # GET /mensajes/1/edit
  def edit
  end

  # POST /mensajes
  # POST /mensajes.json
  def create
    @mensaje = Mensaje.new(mensaje_params)

    respond_to do |format|
      if @mensaje.save
        format.html { redirect_to @mensaje, notice: 'Mensaje was successfully created.' }
        format.json { render :show, status: :created, location: @mensaje }
      else
        format.html { render :new }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensajes/1
  # PATCH/PUT /mensajes/1.json
  def update
    respond_to do |format|
      if @mensaje.update(mensaje_params)
        format.html { redirect_to @mensaje, notice: 'Mensaje was successfully updated.' }
        format.json { render :show, status: :ok, location: @mensaje }
      else
        format.html { render :edit }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensajes/1
  # DELETE /mensajes/1.json
  def destroy
    @mensaje.destroy
    respond_to do |format|
      format.html { redirect_to mensajes_url, notice: 'Mensaje was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensaje
      @mensaje = Mensaje.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mensaje_params
      params.require(:mensaje).permit(:De, :Para, :Contenido)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buscar_helper.rb
module BuscarHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/views/buscar/index.html.erb
<div style="padding:5%; background-color: rgba(0, 0, 0, 0.4); text-align: center; color:yellow">
<h1 >Elaborado por: Alexander Garita, Alan Barquero</h1>
</div>
<body style="background-image: url(https://2.bp.blogspot.com/-n8tZVLszGAQ/U6z3as4gyXI/AAAAAAAAGdY/f4GbVsmlhvg/s1600/AutoWallpaper_part_120007.jpg">
<div class="princ" style="float:center; text-align: center;margin: 10%; background-color: rgba(0, 0, 0, 0.4); padding: 30px 90px; color:white; width: 80%; box-sizing: border-box;border-radius: 5px">
  <h1 style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center;width:96%; border:solid; border-radius: 5px; background-color:rgba(255, 0, 0, 0.6); border-color:white; border-width:thin"><b>MENSAJERIA</b></h1>
  <br> 
  <li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4);; border-color:white; border-width:thin">
<%= link_to "LEER MENSAJES", "main/index", method: :get %>
</li>

 <li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4);; border-color:white; border-width:thin">
<%= link_to "NUEVO MENSAJE", "mensajes/new", method: :get %>
 </li>

 <li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4); border-color:white; border-width:thin">
<%= link_to "MANTENIMIENTO MENSAJES", "mensajes", method: :get %>
 </li>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P2p5Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<div style="padding:5%; background-color: rgba(0, 0, 0, 0.4); text-align: center; color:yellow">
<h1 >Elaborado por: Alexander Garita, Alan Barquero</h1>
</div>
<body style="background-image: url(https://2.bp.blogspot.com/-n8tZVLszGAQ/U6z3as4gyXI/AAAAAAAAGdY/f4GbVsmlhvg/s1600/AutoWallpaper_part_120007.jpg">
<div class="princ" style="float:center; text-align: center;margin: 10%; background-color: rgba(0, 0, 0, 0.4); padding: 30px 90px; color:white; width: 80%; box-sizing: border-box;border-radius: 5px">
 
 <div style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(255, 0, 0, 0.6); border-color:white ; border-width:thin">
 
<%= form_tag "/buscar/create", method: :get, remote: true, id: "search-form" do%>

 <%= text_field_tag :keyword, nil, placeholder: "Buscar Mensajes" %> 
   <%= content_tag :button, type: :submit do %>
   Buscar
   <%end%> 
<%end%>

</div>

<br> 

<div id="resultados" style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4); border-color:white ; border-width:thin">
</div>

<br> 

<li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4); border-color:white; border-width:thin">
<%= link_to "MENU PRINCIPAL", "/", method: :get %>
</li>

</div>
</body>

app/views/mensajes/_form.html.erb
<%= form_for(@mensaje) do |f| %>
  <% if @mensaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mensaje.errors.count, "error") %> prohibited this mensaje from being saved:</h2>

      <ul>
      <% @mensaje.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :De %><br>
    <%= f.text_field :De %>
  </div>
  <div class="field">
    <%= f.label :Para %><br>
    <%= f.text_field :Para %>
  </div>
  <div class="field">
    <%= f.label :Contenido %><br>
    <%= f.text_area :Contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mensajes/_mensaje.html.erb
<div>
<strong> MENSAJE </strong>
<table style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 55, 183, 0.6); border-color:white">

<tr style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 40, 1); border-color:white">
        <td style="font-size:15px">PARA</td>
        <td style="font-size:15px">DE</td>
        <td style="font-size:15px">CONTENIDO</td>
		<td style="font-size:15px">MOSTRAR</td>
</tr>

<tr style="margin: 10px; padding: 10px;float:center; font-size:15px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 40, 1); border-color:white">
        <td style="font-size:15px"><%= mensaje.Para %></td>
        <td style="font-size:15px"><%= mensaje.De %></td>
        <td style="font-size:15px"><%= mensaje.Contenido %></td>
        <td style="font-size:15px"><%= link_to 'Show', mensaje %></td>
      
      </tr>

	  </table>
	  



</div>

app/views/mensajes/edit.html.erb
<div class="princ" style="float:center; text-align: center;margin: 10%; background-color: rgba(0, 0, 40, 1); padding: 30px 90px; color:white; width: 80%; box-sizing: border-box;border-radius: 20px">


<h1 style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center;width:96%; border:solid; border-radius: 5px; background-color:blue; border-color:white">EDITAR MENSAJE</h1>
<div style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 132, 0.6);; border-color:white">
<%= render 'form' %>
</div>

<li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 132, 0.6);; border-color:white">
<%= link_to 'MOSTRAR', @mensaje %>
 </li>
<li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 132, 0.6);; border-color:white">
<%= link_to 'VOLVER', mensajes_path %>
 </li>


</div>

app/views/mensajes/index.html.erb
<div style="padding:5%; background-color: rgba(0, 0, 0, 0.4); text-align: center; color:yellow">
<h1 >Elaborado por: Alexander Garita, Alan Barquero</h1>
</div>
<body style="background-image: url(https://2.bp.blogspot.com/-n8tZVLszGAQ/U6z3as4gyXI/AAAAAAAAGdY/f4GbVsmlhvg/s1600/AutoWallpaper_part_120007.jpg">
<div class="princ" style="float:center; text-align: center;margin: 10%; background-color: rgba(0, 0, 0, 0.4); padding: 30px 90px; color:white; width: 80%; box-sizing: border-box;border-radius: 5px" >

<p id="notice"><%= notice %></p>

<h1 style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center;width:96%; border:solid; border-radius: 5px; background-color:rgba(255, 0, 0, 0.6); border-color:white; border-width:thin">CENTRO DE MENSAJES</h1>

<br>

<table style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4); border-color:white; border-width:thin">
  <thead>
    <tr style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4); border-color:white; border-width:thin">
      <th style="font-size:15px">DE</th>
      <th style="font-size:15px">PARA</th>
      <th style="font-size:15px">CONTENIDO</th>
      <th style="font-size:15px"colspan="2"> OPCIONES</th>
    </tr>
  </thead>

  <tbody>
    <% @mensajes.each do |mensaje| %>
      <tr style="margin: 10px; padding: 10px;float:center; font-size:15px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4); border-color:white; border-width:thin">
        <td style="font-size:15px"><%= mensaje.De %></td>
        <td style="font-size:15px"><%= mensaje.Para %></td>
        <td style="font-size:15px"><%= mensaje.Contenido %></td>
        <td style="font-size:15px"><%= link_to 'Edit', edit_mensaje_path(mensaje) %></td>
        <td style="font-size:15px"><%= link_to 'Destroy', mensaje, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4);; border-color:white; border-width:thin ">
<%= link_to "MENU PRINCIPAL", "/", method: :get %>
</li>

</div>
</body>

app/views/mensajes/new.html.erb
<div style="padding:5%; background-color: rgba(0, 0, 0, 0.4); text-align: center; color:yellow">
<h1 >Elaborado por: Alexander Garita, Alan Barquero</h1>
</div>
<body style="background-image: url(https://2.bp.blogspot.com/-n8tZVLszGAQ/U6z3as4gyXI/AAAAAAAAGdY/f4GbVsmlhvg/s1600/AutoWallpaper_part_120007.jpg">
<div class="princ" style="float:center; text-align: center;margin: 10%; background-color: rgba(0, 0, 0, 0.4); padding: 30px 90px; color:white; width: 80%; box-sizing: border-box;border-radius: 5px">

<h1 style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center;width:96%; border:solid; border-radius: 5px; background-color:rgba(255, 0, 0, 0.6); border-color:white; border-width:thin">NUEVO MENSAJE</h1>

<div style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4);; border-color:white; border-width:thin">
<%= render 'form' %>
</div>

<li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4);; border-color:white; border-width:thin">
<%= link_to "MENU PRINCIPAL", "/", method: :get %>
</li>

</div>
</body>

app/views/mensajes/show.html.erb
<div style="padding:5%; background-color: rgba(0, 0, 0, 0.4); text-align: center; color:yellow">
<h1 >Elaborado por: Alexander Garita, Alan Barquero</h1>
</div>
<body style="background-image: url(https://2.bp.blogspot.com/-n8tZVLszGAQ/U6z3as4gyXI/AAAAAAAAGdY/f4GbVsmlhvg/s1600/AutoWallpaper_part_120007.jpg">
<div class="princ" style="float:center; text-align: center;margin: 10%; background-color: rgba(0, 0, 0, 0.4); padding: 30px 90px; color:white; width: 80%; box-sizing: border-box;border-radius: 5px">


<p id="notice"><%= notice %></p>

<div style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4);; border-color:white; border-width:thin">
<p style="font-size:15px">
  <strong>De:</strong>
  <%= @mensaje.De %>
</p>

<p style="font-size:15px">
  <strong>Para:</strong>
  <%= @mensaje.Para %>
</p>

<p style="font-size:15px">
  <strong>Contenido:</strong>
  <%= @mensaje.Contenido %>
</p>
</div>

<li style="margin: 10px; padding: 10px;float:center; font-size:20px; text-align:center; width:96%; border:solid; border-radius: 5px; background-color: rgba(0, 0, 0, 0.4);; border-color:white; border-width:thin">
<%= link_to "MENU PRINCIPAL", "/", method: :get %>
 </li>

</div>
</body>